# Pipeline parameters
pipeline:
  text_vectorizer:
    features:
      - "receiver_clean"
    transform_mode: "inplace"
    transform_suffix: "_vec"
    hyperparams:
      kbest: 50

  naive_bayes:
    features:
      - "*_vec"
    transform_mode: "inplace"
    transform_suffix: "_nb"
    hyperparams:

  random_forest:
    features:
      - "*_nb"
      - "amount"
    transform_mode: "replace"
    transform_suffix: ""
    hyperparams:
      max_depth: 20
      n_estimators: 100
      min_samples_split: 50
      min_samples_leaf: 10
      random_state: 42

# Training parameters
training:
  target_column: "category"
  n_splits: 5
  shuffle: false

# Data parameters
query:
  start_date:
  end_date:
  mock: false

# Evaluation parameters
metrics:
  accuracy:
    reducers: ["mean", "minmax"]
  precision_macro:
    reducers: ["mean", "minmax"]
  recall_macro:
    reducers: ["mean", "minmax"]
  f1_score_macro:
    reducers: ["mean", "minmax"]
  roc_auc_macro:
    reducers: ["mean", "minmax"]
  roc_auc_micro:
    reducers: ["mean", "minmax"]
