# Model parameters
model:
  name: "random_forest"
  hyperparams:
    max_depth: 25
    n_estimators: 100
    min_samples_split: 30
    min_samples_leaf: 5
    random_state: 42

# Transformer parameters
transformer:
  - name: "feature_selector"
    hyperparams:
      features:
        - "receiver"
        - "amount"

  - name: "text_cleaner"
    hyperparams:
      text_column: "receiver"

  - name: "kbest_text_vector"
    hyperparams:
      text_column: "receiver"
      kbest: 50

# Training parameters
training:
  target_column: "category"
  features:
    - "receiver"
    - "amount"
  n_splits: 5
  shuffle: false

# Data parameters
query:
  start_date:
  end_date:
  mock: false

# Evaluation parameters
metrics:
  accuracy:
    reducers: ["mean", "minmax"]
  precision_macro:
    reducers: ["mean", "minmax"]
  recall_macro:
    reducers: ["mean", "minmax"]
  f1_score_macro:
    reducers: ["mean", "minmax"]
  roc_auc_macro:
    reducers: ["mean", "minmax"]
  roc_auc_micro:
    reducers: ["mean", "minmax"]
