# Model parameters
model:
  name: "random_forest"
  hyperparams_file: "random_forest.yaml"

# Preprocessing parameters
preprocessor:
  0: 
    name: "feature_selector"
    hyperparams_file: "feature_selector.yaml"
  1:
    name: "kbest_text_vector"
    hyperparams_file: "kbest_text_vector.yaml"

# Training parameters
training:
  target_column: "category"
  test_size: 0.2
  random_state: 42

# Data parameters
query:
  start_date: '2025-06-01'
  end_date:
  mock: false