name: Train Model

on:
  push:
    branches: [ "main" ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SA_EMAIL }}

      - name: Build & Push Docker image
        run: |
          gcloud builds submit --tag \
          europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ml/train-model:latest

      - name: Deploy Cloud Run Job
        run: |
          gcloud run jobs deploy train-my-model \
            --image=europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ml/train-model:latest \
            --region=europe-north1

      - name: Trigger training job
        run: |
          gcloud run jobs execute train-my-model \
            --region=europe-north1
